version: '3'
services:
#mssql docker
  mobyshop-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Enterprise
    ports:
      - 1401:1433
    networks:
      - mobyshopnet

  mobyshop-api:
    restart: unless-stopped
    build:
      context: .
    environment:
     - ConnectionStrings:DefaultConnection=Server=mobyshop-sql,1433;Database=RS2_Seminarski_IB150114;User=sa;Password=QWElkj132!;ConnectRetryCount=254
    ports:
      - 5000:80
    networks:
      - mobyshopnet    
    links:
      - mobyshop-sql
    depends_on:
      - mobyshop-sql
      
networks:
  mobyshopnet:
    driver: bridge      