// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobyShop.WebAPI;

namespace MobyShop.WebAPI.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210711105557_baza2")]
    partial class baza2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MobyShop.WebAPI.Database.Artikli", b =>
                {
                    b.Property<int>("ArtikalId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cijena");

                    b.Property<int>("KarakteristikeId");

                    b.Property<int>("ModelId");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ProizvodjacId");

                    b.Property<string>("Sifra")
                        .IsRequired();

                    b.Property<byte[]>("Slika");

                    b.Property<byte[]>("SlikaThumb");

                    b.Property<bool?>("Status")
                        .IsRequired();

                    b.HasKey("ArtikalId");

                    b.HasIndex("KarakteristikeId");

                    b.HasIndex("ModelId");

                    b.HasIndex("ProizvodjacId");

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Dobavljaci", b =>
                {
                    b.Property<int>("DobavljacId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa");

                    b.Property<string>("Email");

                    b.Property<string>("Fax");

                    b.Property<string>("KontaktOsoba");

                    b.Property<string>("Napomena");

                    b.Property<string>("Naziv");

                    b.Property<bool>("Status");

                    b.Property<string>("Telefon");

                    b.Property<string>("Web");

                    b.Property<string>("ZiroRacuni");

                    b.HasKey("DobavljacId");

                    b.ToTable("Dobavljaci");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Karakteristike", b =>
                {
                    b.Property<int>("KarakteristikeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Kamera");

                    b.Property<decimal>("Memorija");

                    b.Property<bool>("Novo");

                    b.Property<string>("OperativniSistem");

                    b.Property<decimal>("Procesor");

                    b.Property<decimal>("Ram");

                    b.HasKey("KarakteristikeId");

                    b.ToTable("Karakteristike");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Klijenti", b =>
                {
                    b.Property<int>("KlijentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumRegistracije");

                    b.Property<string>("Email");

                    b.Property<string>("Ime");

                    b.Property<string>("KorisnickoIme");

                    b.Property<string>("LozinkaHash");

                    b.Property<string>("LozinkaSalt");

                    b.Property<string>("Prezime");

                    b.Property<string>("Telefon");

                    b.HasKey("KlijentId");

                    b.ToTable("Klijenti");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Korisnici", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Ime");

                    b.Property<string>("KorisnickoIme");

                    b.Property<string>("LozinkaHash");

                    b.Property<string>("LozinkaSalt");

                    b.Property<string>("Prezime");

                    b.Property<string>("Telefon");

                    b.HasKey("KorisnikId");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.KorisniciUloge", b =>
                {
                    b.Property<int>("KorisnikUlogaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumIzmjene");

                    b.Property<int>("KorisnikId");

                    b.Property<int>("UlogaId");

                    b.HasKey("KorisnikUlogaId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisniciUloge");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Modeli", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ModelId");

                    b.ToTable("Modeli");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Nabavka", b =>
                {
                    b.Property<int>("NabavkaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojNabavke")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("Datum");

                    b.Property<int>("DobavljacId");

                    b.Property<decimal>("IznosRacuna");

                    b.Property<int>("KorisnikId");

                    b.Property<string>("Napomena");

                    b.Property<decimal>("Pdv");

                    b.Property<int>("SkladisteId");

                    b.HasKey("NabavkaId");

                    b.HasIndex("DobavljacId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("SkladisteId");

                    b.ToTable("Nabavka");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.NabavkaStavke", b =>
                {
                    b.Property<int>("NabavkaStavkeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtikalId");

                    b.Property<decimal>("Cijena");

                    b.Property<int>("Kolicina");

                    b.Property<int>("NabavkaId");

                    b.HasKey("NabavkaStavkeId");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("NabavkaId");

                    b.ToTable("NabavkaStavke");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Narudzba", b =>
                {
                    b.Property<int>("NarudzbaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojNarudzbe")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("Datum");

                    b.Property<decimal>("IznosBezPdv");

                    b.Property<decimal>("IznosSaPdv");

                    b.Property<int>("KlijentId");

                    b.Property<int>("KorisnikId");

                    b.Property<bool?>("Otkazano")
                        .IsRequired();

                    b.Property<int>("SkladisteId");

                    b.Property<bool>("Status");

                    b.HasKey("NarudzbaId");

                    b.HasIndex("KlijentId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("SkladisteId");

                    b.ToTable("Narudzba");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.NarudzbaStavke", b =>
                {
                    b.Property<int>("NarudzbaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtikalId");

                    b.Property<decimal>("Cijena");

                    b.Property<int>("Kolicina");

                    b.Property<int>("NarudzbaId");

                    b.Property<decimal?>("Popust");

                    b.HasKey("NarudzbaStavkaId");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("NarudzbaId");

                    b.ToTable("NarudzbaStavke");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Obavijesti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KorisnikId");

                    b.Property<string>("Naslov");

                    b.Property<byte[]>("Slika");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Obavijesti");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Ocjene", b =>
                {
                    b.Property<int>("OcjenaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtikalId");

                    b.Property<DateTime>("Datum");

                    b.Property<int>("KlijentId");

                    b.Property<int>("Ocjena");

                    b.HasKey("OcjenaId");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("KlijentId");

                    b.ToTable("Ocjene");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.PoslanaNarudzba", b =>
                {
                    b.Property<int>("PoslanaNarudzbaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum");

                    b.Property<int>("KlijentId");

                    b.Property<int>("KorisnikId");

                    b.Property<int>("NarudzbaId");

                    b.Property<bool>("Poslano");

                    b.HasKey("PoslanaNarudzbaId");

                    b.HasIndex("KlijentId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("NarudzbaId");

                    b.ToTable("PoslanaNarudzba");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Proizvodjaci", b =>
                {
                    b.Property<int>("ProizvodjacId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.HasKey("ProizvodjacId");

                    b.ToTable("Proizvodjaci");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Skladista", b =>
                {
                    b.Property<int>("SkladisteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa");

                    b.Property<string>("Naziv");

                    b.Property<string>("Opis");

                    b.HasKey("SkladisteId");

                    b.ToTable("Skladista");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Uloge", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Opis")
                        .HasMaxLength(50);

                    b.HasKey("UlogaId");

                    b.ToTable("Uloge");

                    b.HasData(
                        new { UlogaId = 1, Naziv = "Admin", Opis = "Upravljanje sistemom" },
                        new { UlogaId = 2, Naziv = "Prodavac", Opis = "Rad na sistemu" },
                        new { UlogaId = 3, Naziv = "Skladistar", Opis = "Upravljanje robom" }
                    );
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Zahtjevi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumZahtjeva");

                    b.Property<int>("KlijentId");

                    b.Property<string>("Naslov");

                    b.Property<string>("Opis");

                    b.HasKey("Id");

                    b.HasIndex("KlijentId");

                    b.ToTable("Zahtjevi");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.ZahtjeviStavke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KorisnikId");

                    b.Property<string>("Odgovor");

                    b.Property<int>("ZahtjevId");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ZahtjevId");

                    b.ToTable("ZahtjeviStavke");
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Artikli", b =>
                {
                    b.HasOne("MobyShop.WebAPI.Database.Karakteristike", "Karakteristike")
                        .WithMany("Artikli")
                        .HasForeignKey("KarakteristikeId")
                        .HasConstraintName("FK__KarakteristikeArtikli__KarakteristikaId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Modeli", "Modeli")
                        .WithMany("Artikli")
                        .HasForeignKey("ModelId")
                        .HasConstraintName("FK__ModeliArtikli__ModelId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Proizvodjaci", "Proizvodjaci")
                        .WithMany("Artikli")
                        .HasForeignKey("ProizvodjacId")
                        .HasConstraintName("FK__ProizvodjaciArtikli__ProizvodjacId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.KorisniciUloge", b =>
                {
                    b.HasOne("MobyShop.WebAPI.Database.Korisnici", "Korisnik")
                        .WithMany("KorisniciUloge")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__KorisnikUloga_KorisnikId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Uloge", "Uloga")
                        .WithMany("KorisniciUloge")
                        .HasForeignKey("UlogaId")
                        .HasConstraintName("FK__KorisnikUloga_UlogaId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Nabavka", b =>
                {
                    b.HasOne("MobyShop.WebAPI.Database.Dobavljaci", "Dobavljac")
                        .WithMany("Nabavka")
                        .HasForeignKey("DobavljacId")
                        .HasConstraintName("FK__NabavkaDobavljaci_DobavljacId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Korisnici", "Korisnik")
                        .WithMany("Nabavka")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__NabavkaKorisnik_KorisnikId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Skladista", "Skladiste")
                        .WithMany()
                        .HasForeignKey("SkladisteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.NabavkaStavke", b =>
                {
                    b.HasOne("MobyShop.WebAPI.Database.Artikli", "Artikal")
                        .WithMany("NabavkaStavke")
                        .HasForeignKey("ArtikalId")
                        .HasConstraintName("FK__NabavkaStavkeArtikal__ArtikalId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Nabavka", "Nabavka")
                        .WithMany("NabavkaStavke")
                        .HasForeignKey("NabavkaId")
                        .HasConstraintName("FK__NabavkaStavke__NabavkaId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Narudzba", b =>
                {
                    b.HasOne("MobyShop.WebAPI.Database.Klijenti", "Klijent")
                        .WithMany("Narudzbe")
                        .HasForeignKey("KlijentId")
                        .HasConstraintName("FK__KlijentiNarudzbe_KlijentId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Korisnici", "Korisnik")
                        .WithMany("Narudzba")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__KorisnikNarudzbe_KorisnikId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Skladista", "Skladiste")
                        .WithMany()
                        .HasForeignKey("SkladisteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.NarudzbaStavke", b =>
                {
                    b.HasOne("MobyShop.WebAPI.Database.Artikli", "Artikal")
                        .WithMany("NarudzbaStavke")
                        .HasForeignKey("ArtikalId")
                        .HasConstraintName("FK__NarudzbaStavkeArtikal__ArtikaId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Narudzba", "Narudzba")
                        .WithMany("NarudzbaStavke")
                        .HasForeignKey("NarudzbaId")
                        .HasConstraintName("FK__NarudzbaStavke__NarudzbaId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Obavijesti", b =>
                {
                    b.HasOne("MobyShop.WebAPI.Database.Korisnici", "Korisnik")
                        .WithMany("Obavijesti")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Ocjene", b =>
                {
                    b.HasOne("MobyShop.WebAPI.Database.Artikli", "Artikal")
                        .WithMany("Ocjene")
                        .HasForeignKey("ArtikalId")
                        .HasConstraintName("FK__OcjeneArtikli_ArtikalId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Klijenti", "Klijent")
                        .WithMany("Ocjene")
                        .HasForeignKey("KlijentId")
                        .HasConstraintName("FK__OcjeneKlijent_KlijentId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.PoslanaNarudzba", b =>
                {
                    b.HasOne("MobyShop.WebAPI.Database.Klijenti", "Klijent")
                        .WithMany("PoslanaNarudzba")
                        .HasForeignKey("KlijentId")
                        .HasConstraintName("FK__KlijentiPoslanaNarudzba_KlijentId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Korisnici", "Korisnik")
                        .WithMany("PoslanaNarudzba")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__KorisniciPoslanaNarudzba_KorisnikId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Narudzba", "Narudzba")
                        .WithMany("PoslanaNarudzba")
                        .HasForeignKey("NarudzbaId")
                        .HasConstraintName("FK__PoslanaNarudzba_NarudzbaId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.Zahtjevi", b =>
                {
                    b.HasOne("MobyShop.WebAPI.Database.Klijenti", "Klijent")
                        .WithMany("Zahtjevi")
                        .HasForeignKey("KlijentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MobyShop.WebAPI.Database.ZahtjeviStavke", b =>
                {
                    b.HasOne("MobyShop.WebAPI.Database.Korisnici", "Korisnik")
                        .WithMany("ZahtjeviStavke")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MobyShop.WebAPI.Database.Zahtjevi", "Zahtjev")
                        .WithMany("ZahtjeviStavke")
                        .HasForeignKey("ZahtjevId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
